# Generated by Django 5.2.1 on 2025-05-19 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useravatar',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Avatar', 'verbose_name_plural': 'User Avatars'},
        ),
        migrations.CreateModel(
            name='CertificatePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('size', models.PositiveIntegerField(default=0)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='submissions.certificate')),
            ],
            options={
                'verbose_name': 'Certificate PDF',
                'verbose_name_plural': 'Certificate PDFs',
            },
        ),
    ]
