# Generated by Django 5.2.7 on 2025-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[
                            ("thumbup", "👍 Thumbs Up"),
                            ("heart", "❤️ Heart"),
                            ("sad", "😢 Sad"),
                            ("angry", "😡 Angry"),
                            ("laugh", "😂 Laugh"),
                        ],
                        help_text="Type of reaction",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comment Reaction",
                "verbose_name_plural": "Comment Reactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("submission_assigned", "Submission Assigned"),
                            ("submission_phase_changed", "Phase Changed"),
                            ("botanist_approval_needed", "Botanist Approval Needed"),
                            ("finance_approval_needed", "Finance Approval Needed"),
                            ("certificate_generated", "Certificate Generated"),
                            ("invoice_generated", "Invoice Generated"),
                            ("pdf_generation_failed", "PDF Generation Failed"),
                            ("system_maintenance", "System Maintenance"),
                            ("settings_updated", "Settings Updated"),
                            ("mention", "You were mentioned"),
                            ("comment_added", "New Comment"),
                        ],
                        help_text="Type of notification",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Notification title/headline", max_length=255
                    ),
                ),
                ("message", models.TextField(help_text="Notification message body")),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect to when notification is clicked",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was read",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Notification priority level",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this notification expires (optional)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("text", models.CharField(max_length=1500)),
            ],
            options={
                "verbose_name": "Submission Comment",
                "verbose_name_plural": "Submission Comments",
                "ordering": ["-created_at"],
            },
        ),
    ]
