# Generated by Django 5.2.7 on 2025-10-18 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communications", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("submissions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commentreaction",
            name="user",
            field=models.ForeignKey(
                help_text="User who made the reaction",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered this notification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                help_text="User who will receive this notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissioncomment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissioncomment",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissioncomment",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="submissions.submission",
            ),
        ),
        migrations.AddField(
            model_name="submissioncomment",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissioncomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentreaction",
            name="comment",
            field=models.ForeignKey(
                help_text="Comment being reacted to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="communications.submissioncomment",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="communicati_recipie_dd2f99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "created_at"],
                name="communicati_recipie_5da4f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="communicati_notific_8e3688_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentreaction",
            index=models.Index(
                fields=["comment", "reaction"], name="communicati_comment_600fb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentreaction",
            index=models.Index(
                fields=["user", "comment"], name="communicati_user_id_cc409a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentreaction",
            unique_together={("user", "comment")},
        ),
    ]
