import React, { useState } from "react";
import {
	AlertCircle,
	ArrowRight,
	CheckCircle2,
	Clock,
	FileText,
	Mail,
	Send,
	Undo2,
	User,
} from "lucide-react";
import { type SubmissionPhase } from "@/shared/types/backend-api.types";
import { SubmissionsService } from "@/features/submissions/services/submissions.service";
import { Button } from "@/shared/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/shared/components/ui/dialog";
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
} from "@/shared/components/ui/alert-dialog";
import { Label } from "@/shared/components/ui/label";
import { Textarea } from "@/shared/components/ui/textarea";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/shared/components/ui/select";

// Phase descriptions and action button text
const PHASE_INFO: Record<
	SubmissionPhase,
	{
		title: string;
		description: string;
		actionButtonText: string;
		actionButtonIcon: React.ComponentType<{ className?: string }>;
	}
> = {
	data_entry: {
		title: "Data Entry",
		description:
			"Complete the initial form submission with all required information",
		actionButtonText: "Submit for Finance Approval",
		actionButtonIcon: ArrowRight,
	},
	finance_approval: {
		title: "Finance Approval",
		description: "Finance team reviews budget and cost implications",
		actionButtonText: "Approve & Send to Botanist",
		actionButtonIcon: CheckCircle2,
	},
	botanist_review: {
		title: "Botanist Review",
		description:
			"Expert botanist reviews and approves the submission details",
		actionButtonText: "Approve & Generate Documents",
		actionButtonIcon: CheckCircle2,
	},
	documents: {
		title: "Documents",
		description:
			"Generate certificates and invoices for the approved application",
		actionButtonText: "Generate Documents",
		actionButtonIcon: FileText,
	},
	send_emails: {
		title: "Send Emails",
		description: "Send notifications and documents to relevant parties",
		actionButtonText: "Send All Emails",
		actionButtonIcon: Mail,
	},
	complete: {
		title: "Complete",
		description: "Workflow completed successfully. All documents sent",
		actionButtonText: "Completed",
		actionButtonIcon: CheckCircle2,
	},
};

// Permission indicators
const PERMISSION_INFO: Record<
	SubmissionPhase,
	{
		roles: string[];
		description: string;
	}
> = {
	data_entry: {
		roles: ["Finance Officer", "Botanist", "Admin"],
		description:
			"Can be advanced by Finance Officers, Botanists, or Admins",
	},
	finance_approval: {
		roles: ["Finance Officer", "Admin"],
		description: "Can be approved by Finance Officers or Admins",
	},
	botanist_review: {
		roles: ["Botanist", "Admin"],
		description: "Can be approved by Botanists or Admins",
	},
	documents: {
		roles: ["Finance Officer", "Botanist", "Admin"],
		description:
			"Documents can be generated by Finance Officers, Botanists, or Admins",
	},
	send_emails: {
		roles: ["Finance Officer", "Botanist", "Admin"],
		description:
			"Emails can be sent by Finance Officers, Botanists, or Admins",
	},
	complete: {
		roles: [],
		description: "Workflow is complete. No further actions required",
	},
};

// Send-back target phases based on current phase
const SEND_BACK_TARGETS: Record<SubmissionPhase, SubmissionPhase[]> = {
	data_entry: [],
	finance_approval: ["data_entry"],
	botanist_review: ["data_entry", "finance_approval"],
	documents: ["data_entry", "finance_approval", "botanist_review"],
	send_emails: [
		"data_entry",
		"finance_approval",
		"botanist_review",
		"documents",
	],
	complete: [],
};

export interface PhaseActionsBarProps {
	currentPhase: SubmissionPhase;
	viewingPhase: SubmissionPhase;
	isCurrentPhase: boolean;
	userRole: "botanist" | "finance" | "none";
	isAdmin: boolean;
	isAdvancing: boolean;
	isSendingBack: boolean;
	onAdvance: () => Promise<void>;
	onSendBack: (targetPhase: SubmissionPhase, reason: string) => Promise<void>;
}

export const PhaseActionsBar: React.FC<PhaseActionsBarProps> = ({
	currentPhase,
	viewingPhase,
	isCurrentPhase,
	userRole,
	isAdmin,
	isAdvancing,
	isSendingBack,
	onAdvance,
	onSendBack,
}) => {
	const [showSendBackDialog, setShowSendBackDialog] = useState(false);
	const [showConfirmDialog, setShowConfirmDialog] = useState(false);
	const [sendBackReason, setSendBackReason] = useState("");
	const [selectedTargetPhase, setSelectedTargetPhase] =
		useState<SubmissionPhase | null>(null);

	const phaseInfo = PHASE_INFO[viewingPhase];
	const permissionInfo = PERMISSION_INFO[viewingPhase];

	// Determine if user can advance from current phase
	const canAdvance = (): boolean => {
		if (!isCurrentPhase) return false;
		if (currentPhase === "complete") return false;
		if (isAdmin) return true;

		const permissions: Record<SubmissionPhase, string[]> = {
			data_entry: ["botanist", "finance"],
			finance_approval: ["finance"],
			botanist_review: ["botanist"],
			documents: ["botanist", "finance"],
			send_emails: ["botanist", "finance"],
			complete: [],
		};

		return permissions[currentPhase].includes(userRole);
	};

	// Determine if user can send back from current phase
	const canSendBack = (): boolean => {
		if (!isCurrentPhase) return false;
		if (isAdmin) return SEND_BACK_TARGETS[currentPhase].length > 0;

		const sendBackPermissions: Record<SubmissionPhase, string[]> = {
			data_entry: [],
			finance_approval: ["finance"],
			botanist_review: ["botanist"],
			documents: ["botanist", "finance"],
			send_emails: ["botanist", "finance"],
			complete: [],
		};

		return (
			sendBackPermissions[currentPhase].includes(userRole) &&
			SEND_BACK_TARGETS[currentPhase].length > 0
		);
	};

	// Get phase status
	const getPhaseStatus = (): {
		label: string;
		color: string;
		icon: React.ComponentType<{ className?: string }>;
	} => {
		if (currentPhase === "complete") {
			return {
				label: "Completed",
				color: "text-emerald-600",
				icon: CheckCircle2,
			};
		}

		if (isCurrentPhase) {
			return {
				label: "Active",
				color: "text-blue-600",
				icon: Clock,
			};
		}

		return {
			label: "Viewing History",
			color: "text-gray-600",
			icon: AlertCircle,
		};
	};

	const status = getPhaseStatus();
	const StatusIcon = status.icon;
	const ActionIcon = phaseInfo.actionButtonIcon;

	const handleAdvanceClick = () => {
		// Show confirmation dialog for critical actions
		if (
			currentPhase === "finance_approval" ||
			currentPhase === "botanist_review" ||
			currentPhase === "send_emails"
		) {
			setShowConfirmDialog(true);
		} else {
			onAdvance();
		}
	};

	const handleConfirmAdvance = async () => {
		setShowConfirmDialog(false);
		await onAdvance();
	};

	const handleSendBackClick = () => {
		setSendBackReason("");
		setSelectedTargetPhase(SEND_BACK_TARGETS[currentPhase][0] || null);
		setShowSendBackDialog(true);
	};

	const handleConfirmSendBack = async () => {
		if (!selectedTargetPhase || !sendBackReason.trim()) return;

		setShowSendBackDialog(false);
		await onSendBack(selectedTargetPhase, sendBackReason);
	};

	const sendBackTargets = SEND_BACK_TARGETS[currentPhase];

	return (
		<>
			<div className="bg-white rounded-xl shadow-lg p-6 md:p-8">
				{/* Phase Info Section */}
				<div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6">
					<div className="flex-1">
						<div className="flex items-center gap-3 mb-2">
							<h2 className="text-2xl font-bold text-gray-900">
								{phaseInfo.title}
							</h2>
							<div
								className={`flex items-center gap-1.5 px-3 py-1 rounded-full bg-gray-100 ${status.color}`}
							>
								<StatusIcon className="w-4 h-4" />
								<span className="text-sm font-medium">
									{status.label}
								</span>
							</div>
						</div>
						<p className="text-gray-600">{phaseInfo.description}</p>
					</div>

					{/* Permission Indicator */}
					{isCurrentPhase && (
						<div className="flex items-start gap-2 px-4 py-3 bg-blue-50 rounded-lg border border-blue-200">
							<User className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" />
							<div>
								<p className="text-sm font-medium text-blue-900">
									Who can edit:
								</p>
								<p className="text-sm text-blue-700">
									{permissionInfo.roles.join(", ") ||
										"No one"}
								</p>
							</div>
						</div>
					)}
				</div>

				{/* Action Buttons */}
				{isCurrentPhase && currentPhase !== "complete" && (
					<div className="flex flex-col sm:flex-row gap-3">
						{/* Send Back Button */}
						{canSendBack() && (
							<Button
								variant="outline"
								onClick={handleSendBackClick}
								disabled={isSendingBack || isAdvancing}
								className="w-full sm:w-auto min-h-[44px] border-red-300 text-red-700 hover:bg-red-50 hover:text-red-800 hover:border-red-400"
							>
								<Undo2 className="w-4 h-4 mr-2" />
								{isSendingBack
									? "Sending Back..."
									: "Send Back"}
							</Button>
						)}

						{/* Advance Button */}
						{canAdvance() && (
							<Button
								onClick={handleAdvanceClick}
								disabled={isAdvancing || isSendingBack}
								className="w-full sm:w-auto min-h-[44px] bg-emerald-600 hover:bg-emerald-700 text-white"
							>
								<ActionIcon className="w-4 h-4 mr-2" />
								{isAdvancing
									? "Processing..."
									: phaseInfo.actionButtonText}
							</Button>
						)}

						{/* Admin Override Indicator */}
						{isAdmin && (
							<div className="flex items-center gap-2 px-3 py-2 bg-amber-50 rounded-lg border border-amber-200 text-sm text-amber-800 w-full sm:w-auto">
								<AlertCircle className="w-4 h-4 flex-shrink-0" />
								<span className="font-medium">
									Admin Override Active
								</span>
							</div>
						)}
					</div>
				)}

				{/* Viewing History Message */}
				{!isCurrentPhase && (
					<div className="flex items-center gap-2 px-4 py-3 bg-gray-50 rounded-lg border border-gray-200">
						<AlertCircle className="w-5 h-5 text-gray-600" />
						<p className="text-sm text-gray-700">
							You are viewing historical data from a previous
							phase. Actions are disabled.
						</p>
					</div>
				)}
			</div>

			{/* Send Back Dialog */}
			<Dialog
				open={showSendBackDialog}
				onOpenChange={setShowSendBackDialog}
			>
				<DialogContent className="sm:max-w-[500px]">
					<DialogHeader>
						<DialogTitle>Send Back Submission</DialogTitle>
						<DialogDescription>
							Send this submission back to an earlier phase for
							corrections or additional information.
						</DialogDescription>
					</DialogHeader>

					<div className="space-y-4 py-4">
						{/* Target Phase Selection */}
						<div className="space-y-2">
							<Label htmlFor="target-phase">
								Send back to phase
							</Label>
							<Select
								value={selectedTargetPhase || ""}
								onValueChange={(value) =>
									setSelectedTargetPhase(
										value as SubmissionPhase
									)
								}
							>
								<SelectTrigger id="target-phase">
									<SelectValue placeholder="Select target phase" />
								</SelectTrigger>
								<SelectContent>
									{sendBackTargets.map((phase) => (
										<SelectItem key={phase} value={phase}>
											{SubmissionsService.getPhaseDisplay(
												phase
											)}
										</SelectItem>
									))}
								</SelectContent>
							</Select>
						</div>

						{/* Reason Textarea */}
						<div className="space-y-2">
							<Label htmlFor="reason" className="required">
								Reason for sending back
							</Label>
							<Textarea
								id="reason"
								placeholder="Explain why this submission needs to be sent back..."
								value={sendBackReason}
								onChange={(e) =>
									setSendBackReason(e.target.value)
								}
								rows={4}
								className={
									sendBackReason.trim() === ""
										? "border-red-300"
										: ""
								}
							/>
							{sendBackReason.trim() === "" && (
								<p className="text-sm text-red-600">
									Reason is required
								</p>
							)}
						</div>
					</div>

					<DialogFooter>
						<Button
							variant="outline"
							onClick={() => setShowSendBackDialog(false)}
							disabled={isSendingBack}
						>
							Cancel
						</Button>
						<Button
							onClick={handleConfirmSendBack}
							disabled={
								!selectedTargetPhase ||
								!sendBackReason.trim() ||
								isSendingBack
							}
							className="bg-red-600 hover:bg-red-700 text-white"
						>
							<Send className="w-4 h-4 mr-2" />
							{isSendingBack ? "Sending Back..." : "Send Back"}
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>

			{/* Confirmation Dialog for Critical Actions */}
			<AlertDialog
				open={showConfirmDialog}
				onOpenChange={setShowConfirmDialog}
			>
				<AlertDialogContent>
					<AlertDialogHeader>
						<AlertDialogTitle>Confirm Action</AlertDialogTitle>
						<AlertDialogDescription>
							{currentPhase === "finance_approval" &&
								"Are you sure you want to approve this submission financially and send it to the botanist for review?"}
							{currentPhase === "botanist_review" &&
								"Are you sure you want to approve this botanical assessment and proceed to document generation?"}
							{currentPhase === "send_emails" &&
								"Are you sure you want to send all emails? This will notify all relevant parties and complete the workflow."}
						</AlertDialogDescription>
					</AlertDialogHeader>
					<AlertDialogFooter>
						<AlertDialogCancel disabled={isAdvancing}>
							Cancel
						</AlertDialogCancel>
						<AlertDialogAction
							onClick={handleConfirmAdvance}
							disabled={isAdvancing}
							className="bg-emerald-600 hover:bg-emerald-700"
						>
							{isAdvancing ? "Processing..." : "Confirm"}
						</AlertDialogAction>
					</AlertDialogFooter>
				</AlertDialogContent>
			</AlertDialog>
		</>
	);
};
