version: "3.8"

services:
    backend:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/app
        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/client
        environment:
            - VITE_PRODUCTION_BASE_URL=http://localhost:3000/
            - VITE_PRODUCTION_BACKEND_API_URL=http://localhost:8000/api/v1/
        depends_on:
            - backend

    db:
        image: postgres:16-alpine
        environment:
            - POSTGRES_DB=cannabis
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
