# Generated by Django 5.2.1 on 2025-05-19 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_dbcastaffprofile_remove_user_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('seed', 'Seed/s'), ('seedling', 'Seedling/s'), ('plant', 'Plant/s'), ('plant_striking', 'Plant Striking/s'), ('poppy_capsule', 'Poppy Capsule/s'), ('stem', 'Stem/s'), ('root_ball', 'Root Ball/s'), ('mushroom', 'Mushroom/s'), ('tin', 'Tin/s'), ('unknown', 'Unknown')], default='plant')),
                ('units', models.PositiveIntegerField()),
                ('police_reference_number', models.CharField(max_length=17)),
                ('police_property_number', models.CharField(max_length=4)),
                ('seal_no', models.CharField(max_length=50)),
                ('new_seal_no', models.CharField(max_length=50)),
                ('botanist_determination', models.CharField(default='cannabis', verbose_name=[('degraded', 'Degraded'), ('cannabis', 'Cannabis Sativa')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dbca_submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='users.dbcastaffprofile')),
                ('police_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_as_officer', to='users.policestaffprofile')),
                ('police_submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_on_behalf', to='users.policestaffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('identification_fee', models.PositiveIntegerField(default=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
