# Generated by Django 5.2.6 on 2025-09-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="legacy_id",
            field=models.CharField(
                blank=True,
                help_text="Original row_id from ETL processing for cannabis data import",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="drugbag",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("plant", "Plant Material"),
                    ("plant_material", "Plant Material (Generic)"),
                    ("plant_striking", "Plant Striking"),
                    ("cutting", "Cutting"),
                    ("stalk", "Stalk"),
                    ("stem", "Stem"),
                    ("seed", "Seed"),
                    ("seed_material", "Seed Material"),
                    ("unknown_seed", "Unknown Seed"),
                    ("seedling", "Seedling"),
                    ("head", "Head"),
                    ("rootball", "Rootball"),
                    ("poppy", "Poppy"),
                    ("poppy_plant", "Poppy Plant"),
                    ("poppy_capsule", "Poppy Capsule"),
                    ("poppy_head", "Poppy Head"),
                    ("poppy_seed", "Poppy Seed"),
                    ("mushroom", "Mushroom"),
                    ("tablet", "Tablet"),
                    ("resin", "Resin/Hash"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                    ("unsure", "Unsure"),
                ],
                default="plant",
                max_length=20,
            ),
        ),
    ]
