# Generated by Django 5.2.6 on 2025-09-24 07:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police", "0001_initial"),
        ("submissions", "0002_add_legacy_id_and_expand_content_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drugbag",
            old_name="new_seal_tag_number",
            new_name="new_seal_tag_numbers",
        ),
        migrations.RenameField(
            model_name="drugbag",
            old_name="seal_tag_number",
            new_name="seal_tag_numbers",
        ),
        migrations.AlterUniqueTogether(
            name="drugbag",
            unique_together={("submission", "seal_tag_numbers")},
        ),
        migrations.RemoveField(
            model_name="submission",
            name="assessment_notes",
        ),
        migrations.AddField(
            model_name="botanicalassessment",
            name="confidence_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Assessment confidence score (0.00-1.00) from botanical analysis",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="botanicalassessment",
            name="handed_to_officer",
            field=models.CharField(
                blank=True,
                help_text="Name of officer who received the resealed bags",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="botanicalassessment",
            name="officer_present_during_assessment",
            field=models.BooleanField(
                default=False,
                help_text="Whether the receiving officer was present during the assessment",
            ),
        ),
        migrations.AddField(
            model_name="botanicalassessment",
            name="requires_manual_review",
            field=models.BooleanField(
                default=False,
                help_text="Whether this assessment requires manual review for quality control",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="original_cert_date",
            field=models.CharField(
                blank=True,
                help_text="Original certificate date format from source document (ETL import)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="internal_comments",
            field=models.TextField(
                blank=True,
                help_text="Any internal comments not showing on certificate",
                null=True,
                verbose_name="Internal Comments",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="original_receipt_date",
            field=models.CharField(
                blank=True,
                help_text="Original receipt date format from source document (ETL import)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="station",
            field=models.ForeignKey(
                blank=True,
                help_text="The station submission is for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_involvement",
                to="police.policestation",
            ),
        ),
        migrations.AlterField(
            model_name="botanicalassessment",
            name="assessment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the botanical assessment was performed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="drugbag",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("plant", "Plant Material"),
                    ("plant_material", "Plant Material (Generic)"),
                    ("cutting", "Cutting"),
                    ("stalk", "Stalk"),
                    ("stem", "Stem"),
                    ("seed", "Seed"),
                    ("seed_material", "Seed Material"),
                    ("unknown_seed", "Unknown Seed"),
                    ("seedling", "Seedling"),
                    ("head", "Head"),
                    ("rootball", "Rootball"),
                    ("poppy", "Poppy"),
                    ("poppy_plant", "Poppy Plant"),
                    ("poppy_capsule", "Poppy Capsule"),
                    ("poppy_head", "Poppy Head"),
                    ("poppy_seed", "Poppy Seed"),
                    ("mushroom", "Mushroom"),
                    ("tablet", "Tablet"),
                    ("unknown", "Unknown"),
                    ("unsure", "Unsure"),
                ],
                default="plant",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="drugbag",
            name="property_reference",
            field=models.CharField(
                blank=True,
                help_text="Police property reference number",
                max_length=20,
                null=True,
                verbose_name="Property Reference",
            ),
        ),
        migrations.RemoveField(
            model_name="drugbag",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="drugbag",
            name="suspected_as",
        ),
    ]
