# Generated by Django 5.2.7 on 2025-10-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="case_number",
            field=models.CharField(
                blank=True,
                help_text="Unique case identifier (can be empty for drafts)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="security_movement_envelope",
            field=models.CharField(
                blank=True,
                help_text="Security Movement Envelope number for the bags (can be empty for drafts)",
                max_length=20,
                verbose_name="Security Movement Envelope",
            ),
        ),
    ]
