# Generated by Django 5.2.6 on 2025-09-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_add_etl_enhancement_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botanicalassessment",
            name="confidence_score",
        ),
        migrations.RemoveField(
            model_name="botanicalassessment",
            name="handed_to_officer",
        ),
        migrations.RemoveField(
            model_name="botanicalassessment",
            name="officer_present_during_assessment",
        ),
        migrations.RemoveField(
            model_name="botanicalassessment",
            name="requires_manual_review",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="original_cert_date",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="original_receipt_date",
        ),
    ]
