# Generated by Django 5.2.6 on 2025-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_remove_unnecessary_etl_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botanicalassessment",
            name="determination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending Assessment"),
                    ("cannabis_sativa", "Cannabis sativa"),
                    ("cannabis_indica", "Cannabis indica"),
                    ("cannabis_hybrid", "Cannabis (hybrid)"),
                    ("mixed", "Mixed"),
                    ("papaver_somniferum", "Papaver somniferum"),
                    ("degraded", "Degraded"),
                    ("not_cannabis", "Not Cannabis"),
                    ("unidentifiable", "Unidentifiable"),
                    ("inconclusive", "Inconclusive"),
                ],
                help_text="Botanical determination result",
                max_length=50,
                null=True,
            ),
        ),
    ]
