# Generated by Django 5.2.13 on 2026-04-24 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        help_text="PNG or SVG signature image with transparent background",
                        upload_to="signatures/",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("image/png", "PNG"), ("image/svg+xml", "SVG")],
                        help_text="MIME type of the stored image",
                        max_length=20,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Image width in pixels (PNG only)",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Image height in pixels (PNG only)",
                        null=True,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the file contents",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature",
                "verbose_name_plural": "Signatures",
            },
        ),
        migrations.CreateModel(
            name="SignatureAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("integrity_failure", "Integrity Failure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the signature at time of action",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size at time of action", null=True
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash at time of action",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signature_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose signature was acted upon",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature Audit Log",
                "verbose_name_plural": "Signature Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="signatures__user_id_a2afbf_idx",
                    )
                ],
            },
        ),
    ]
