# Generated by Django 5.2.13 on 2026-04-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0002_add_sign_action_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signatureauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("sign", "Sign"),
                    ("unlock", "Unlock"),
                    ("integrity_failure", "Integrity Failure"),
                ],
                max_length=20,
            ),
        ),
    ]
