apiVersion: apps/v1
kind: Deployment
metadata:
  name: cannabis-deployment
  labels:
    app: cannabis-prod
spec:
  selector:
    matchLabels:
      app: cannabis-prod
  template:
    metadata:
      labels:
        app: cannabis-prod
    spec:
      containers:
        - name: cannabis-backend
          envFrom:
            - secretRef:
                name: cannabis-env-prod
          volumeMounts:
            - name: prince2-license-prod
              mountPath: /usr/lib/prince/license
              readOnly: true
        - name: cannabis-frontend
          imagePullPolicy: IfNotPresent
      volumes:
        - name: prince2-license-prod
          configMap:
            defaultMode: 420
            name: prince2-license-prod
