# Generated by Django 5.2.7 on 2025-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Defendant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name or given names.",
                        max_length=100,
                        null=True,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Last name or surname.",
                        max_length=100,
                        verbose_name="Last Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Defendant",
                "verbose_name_plural": "Defendants",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
