# Generated by Django 5.2.7 on 2025-10-18 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("defendants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="defendant",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="defendant",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="defendant",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="defendant",
            index=models.Index(
                fields=["last_name"], name="defendants__last_na_eec248_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="defendant",
            index=models.Index(
                fields=["first_name"], name="defendants__first_n_2f12a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="defendant",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="defendants__last_na_619e53_idx",
            ),
        ),
    ]
