# Generated by Django 6.0.5 on 2026-05-17 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defendants", "0003_rename_first_name_to_given_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defendant",
            options={
                "ordering": ["last_name", "given_names"],
                "verbose_name": "Defendant",
                "verbose_name_plural": "Defendants",
            },
        ),
        migrations.RemoveIndex(
            model_name="defendant",
            name="defendants__first_n_2f12a5_idx",
        ),
        migrations.RemoveIndex(
            model_name="defendant",
            name="defendants__last_na_619e53_idx",
        ),
        migrations.AlterField(
            model_name="defendant",
            name="given_names",
            field=models.CharField(
                blank=True,
                help_text="Given names (may be multiple, e.g. 'Van Ngoc').",
                max_length=100,
                null=True,
                verbose_name="Given Names",
            ),
        ),
        migrations.AddIndex(
            model_name="defendant",
            index=models.Index(
                fields=["given_names"], name="defendants__given_n_388166_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="defendant",
            index=models.Index(
                fields=["last_name", "given_names"],
                name="defendants__last_na_c0c60f_idx",
            ),
        ),
    ]
