# Generated by Django 6.1.1 on 2026-10-01 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defendants", "0004_alter_defendant_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="defendant",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in practice mode. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AddField(
            model_name="defendant",
            name="practice_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this practice record; null for real data. A user only ever sees their own practice data.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_defendants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
