# Generated by Django 5.2.7 on 2025-10-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="send_emails_to_self",
            field=models.BooleanField(
                default=True,
                help_text="Send invitation emails to the admin instead of actual recipients (for testing)",
            ),
        ),
    ]
