# Generated by Django 5.2.7 on 2025-10-22 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_add_send_emails_to_self"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="last_modified_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp of last modification"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified these settings",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
