# Generated by Django 6.0.6 on 2026-06-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_add_email_testing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="document_email_address",
            field=models.EmailField(
                blank=True,
                help_text="Email address to send completed documents to. Falls back to forward_certificate_emails_to.",
                max_length=254,
                null=True,
            ),
        ),
    ]
