# Generated by Django 6.0.6 on 2026-06-29 02:59

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_add_document_email_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="cost_per_kilometer_fuel",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.75"),
                help_text="Cost per kilometer for fuel in dollars",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
