# Generated by Django 6.0.6 on 2026-06-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_systemsettings_cost_per_kilometer_fuel"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="batch_counter",
            field=models.PositiveIntegerField(
                default=1, help_text="Next batch number to assign"
            ),
        ),
    ]
