# Generated by Django 6.0.6 on 2026-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_systemsettings_batch_counter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="call_out_fee",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="cost_per_forensic_hour",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="cost_per_kilometer_fuel",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="document_email_address",
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="forward_certificate_emails_to",
            field=models.EmailField(
                default="jarid.prince@dbca.wa.gov.au",
                help_text="Fallback recipient for system emails (invites, password reset)",
                max_length=254,
            ),
        ),
    ]
