# Generated by Django 6.0.6 on 2026-06-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_drop_communications_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="invoice_counter",
        ),
    ]
