# Generated by Django 6.0.6 on 2026-06-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_remove_systemsettings_invoice_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="ocr_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the Priority 3 form OCR upload appears on case creation and processing to optionally prefill case data.",
            ),
        ),
    ]
