# Generated by Django 6.1.1 on 2026-09-17 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_systemsettings_ocr_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="default_approved_botanist",
            field=models.ForeignKey(
                blank=True,
                help_text="Pre-selected as the approved botanist on new cases. Leave unset to start each case with no botanist chosen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_botanist_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
