# Generated by Django 5.2.13 on 2026-04-24 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_alter_submission_case_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="file_hash_at_signing",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of the signature image at signing time",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="signature_embedded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the signature was embedded in the PDF",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="signature_used_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of the Signature record used when signing this certificate",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who signed this certificate",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signed_certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
