# Generated by Django 5.2.13 on 2026-04-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_certificate_file_hash_at_signing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="phase",
            field=models.CharField(
                choices=[
                    ("data_entry", "Data Entry"),
                    ("finance_approval", "Finance Approval"),
                    ("botanist_review", "Botanist Review"),
                    ("documents", "Documents"),
                    ("botanist_signoff", "Botanist Sign-Off"),
                    ("invoicing", "Invoice Generation"),
                    ("send_emails", "Send Emails"),
                    ("complete", "Complete"),
                ],
                default="data_entry",
                help_text="Current phase of the submission workflow",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="submissionphasehistory",
            name="from_phase",
            field=models.CharField(
                choices=[
                    ("data_entry", "Data Entry"),
                    ("finance_approval", "Finance Approval"),
                    ("botanist_review", "Botanist Review"),
                    ("documents", "Documents"),
                    ("botanist_signoff", "Botanist Sign-Off"),
                    ("invoicing", "Invoice Generation"),
                    ("send_emails", "Send Emails"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the submission was in before this transition",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="submissionphasehistory",
            name="to_phase",
            field=models.CharField(
                choices=[
                    ("data_entry", "Data Entry"),
                    ("finance_approval", "Finance Approval"),
                    ("botanist_review", "Botanist Review"),
                    ("documents", "Documents"),
                    ("botanist_signoff", "Botanist Sign-Off"),
                    ("invoicing", "Invoice Generation"),
                    ("send_emails", "Send Emails"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the submission moved to",
                max_length=30,
            ),
        ),
    ]
