# Generated by Django 5.2.13 on 2026-04-24 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_add_botanist_signoff_and_invoicing_phases"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="When True, the unsigned PDF cannot be regenerated",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the certificate was locked after signing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="signed_pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Signed PDF certificate with embedded signature",
                null=True,
                upload_to="certificates/signed/",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="signed_pdf_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Size of the signed PDF in bytes"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="unlocked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last unlocked this certificate (audit trail)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlocked_certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
