# Generated by Django 6.0.5 on 2026-05-17 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defendants", "0004_alter_defendant_options_and_more"),
        ("police", "0002_initial"),
        ("submissions", "0010_rename_submission_to_case"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={
                "ordering": ["-received"],
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
            },
        ),
        migrations.AlterModelOptions(
            name="casedraft",
            options={
                "verbose_name": "Case Draft",
                "verbose_name_plural": "Case Drafts",
            },
        ),
        migrations.RenameIndex(
            model_name="casephasehistory",
            new_name="submissions_submiss_fe0b7e_idx",
            old_name="submissions_submiss_5dfe1c_idx",
        ),
        migrations.AlterField(
            model_name="additionalinvoicefee",
            name="submission",
            field=models.ForeignKey(
                help_text="The case this fee relates to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_fees",
                to="submissions.case",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="approved_botanist",
            field=models.ForeignKey(
                blank=True,
                help_text="The approved botanist handling this case",
                limit_choices_to={"role": "botanist"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="botanist_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="defendants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Defendants involved in this case",
                related_name="cases",
                to="defendants.defendant",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="finance_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="The finance officer handling this case",
                limit_choices_to={"role": "finance"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finance_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="phase",
            field=models.CharField(
                choices=[
                    ("data_entry", "Data Entry"),
                    ("finance_approval", "Finance Approval"),
                    ("botanist_review", "Botanist Review"),
                    ("documents", "Documents"),
                    ("botanist_signoff", "Botanist Sign-Off"),
                    ("invoicing", "Invoice Generation"),
                    ("send_emails", "Send Emails"),
                    ("complete", "Complete"),
                ],
                default="data_entry",
                help_text="Current phase of the case workflow",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="requesting_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="The original officer requesting the case",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_requested",
                to="police.policeofficer",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="station",
            field=models.ForeignKey(
                blank=True,
                help_text="The station this case is for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_involvement",
                to="police.policestation",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="submitting_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="The officer submitting on behalf of requesting officer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_made",
                to="police.policeofficer",
            ),
        ),
        migrations.AlterField(
            model_name="casedraft",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_draft",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="from_phase",
            field=models.CharField(
                choices=[
                    ("data_entry", "Data Entry"),
                    ("finance_approval", "Finance Approval"),
                    ("botanist_review", "Botanist Review"),
                    ("documents", "Documents"),
                    ("botanist_signoff", "Botanist Sign-Off"),
                    ("invoicing", "Invoice Generation"),
                    ("send_emails", "Send Emails"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case was in before this transition",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="submission",
            field=models.ForeignKey(
                help_text="The case this history entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phase_history",
                to="submissions.case",
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="to_phase",
            field=models.CharField(
                choices=[
                    ("data_entry", "Data Entry"),
                    ("finance_approval", "Finance Approval"),
                    ("botanist_review", "Botanist Review"),
                    ("documents", "Documents"),
                    ("botanist_signoff", "Botanist Sign-Off"),
                    ("invoicing", "Invoice Generation"),
                    ("send_emails", "Send Emails"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case moved to",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="user",
            field=models.ForeignKey(
                help_text="User who performed this action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_phase_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="drugbag",
            name="submission",
            field=models.ForeignKey(
                help_text="The case this bag belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bags",
                to="submissions.case",
            ),
        ),
    ]
