# Generated by Django 6.0.6 on 2026-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0012_update_phase_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casephasehistory",
            name="from_phase",
            field=models.CharField(
                choices=[
                    ("assessment", "Awaiting Assessment"),
                    ("data_entry", "Awaiting Data Entry"),
                    ("unsigned_generation", "Awaiting Unsigned Cert"),
                    ("botanist_signoff", "Awaiting Signature"),
                    ("invoicing", "Awaiting Invoice"),
                    ("send_emails", "Awaiting Email"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case was in before this transition",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="to_phase",
            field=models.CharField(
                choices=[
                    ("assessment", "Awaiting Assessment"),
                    ("data_entry", "Awaiting Data Entry"),
                    ("unsigned_generation", "Awaiting Unsigned Cert"),
                    ("botanist_signoff", "Awaiting Signature"),
                    ("invoicing", "Awaiting Invoice"),
                    ("send_emails", "Awaiting Email"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case moved to",
                max_length=30,
            ),
        ),
    ]
