# Generated by Django 6.0.6 on 2026-06-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0013_alter_casephasehistory_from_phase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="phase",
            field=models.CharField(
                choices=[
                    ("case_creation", "Case Creation"),
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("botanist_signoff", "Botanist Sign-Off"),
                    ("invoicing", "Invoicing"),
                    ("send_emails", "Email"),
                    ("complete", "Complete"),
                ],
                default="case_creation",
                help_text="Current phase of the case workflow",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="from_phase",
            field=models.CharField(
                choices=[
                    ("case_creation", "Case Creation"),
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("botanist_signoff", "Botanist Sign-Off"),
                    ("invoicing", "Invoicing"),
                    ("send_emails", "Email"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case was in before this transition",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="to_phase",
            field=models.CharField(
                choices=[
                    ("case_creation", "Case Creation"),
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("botanist_signoff", "Botanist Sign-Off"),
                    ("invoicing", "Invoicing"),
                    ("send_emails", "Email"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case moved to",
                max_length=30,
            ),
        ),
    ]
