# Generated by Django 6.0.6 on 2026-06-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0015_migrate_data_entry_to_new_phases"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="additional_notes",
            field=models.TextField(
                blank=True,
                help_text="Section C certificate content (additional notes for the examining botanist)",
                null=True,
                verbose_name="Additional Notes",
            ),
        ),
    ]
