# Generated by Django 6.0.6 on 2026-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0016_case_additional_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="pdf_size",
        ),
        migrations.AddField(
            model_name="certificate",
            name="unsigned_pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Unsigned PDF certificate",
                null=True,
                upload_to="certificates/",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="unsigned_pdf_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Size of the unsigned PDF in bytes"
            ),
        ),
    ]
