# Generated by Django 6.0.6 on 2026-06-18 05:16

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0017_remove_certificate_pdf_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalinvoicefee",
            name="units",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Number of units (km for fuel, hours for forensic, times for call out)",
                max_digits=10,
            ),
        ),
    ]
