# Generated by Django 6.0.6 on 2026-06-30 08:14

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0018_alter_additionalinvoicefee_units_to_decimal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="last_actioned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last performed a workflow action on this case",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_actioned_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="bags",
            field=models.ManyToManyField(
                blank=True,
                help_text="The drug bags covered by this certificate (up to 5)",
                related_name="certificates",
                to="submissions.drugbag",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="certified_date",
            field=models.DateField(
                blank=True,
                help_text="Date the certificate was certified, shown on the PDF",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Generated certificate PDF",
                null=True,
                upload_to="certificates/",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="pdf_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Size of the certificate PDF in bytes"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="phase",
            field=models.CharField(
                choices=[
                    ("case_creation", "Case Creation"),
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("batching", "Batching"),
                    ("complete", "Complete"),
                ],
                default="case_creation",
                help_text="Current phase of the case workflow",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="from_phase",
            field=models.CharField(
                choices=[
                    ("case_creation", "Case Creation"),
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("batching", "Batching"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case was in before this transition",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="to_phase",
            field=models.CharField(
                choices=[
                    ("case_creation", "Case Creation"),
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("batching", "Batching"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case moved to",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="unsigned_pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Unsigned PDF certificate (legacy)",
                null=True,
                upload_to="certificates/",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="unsigned_pdf_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Size of the unsigned PDF in bytes (legacy)"
            ),
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated batch number (e.g., BATCH2025-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "cert_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Certificate rate captured at batch time",
                        max_digits=8,
                    ),
                ),
                (
                    "bag_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Bag identification rate captured at batch time",
                        max_digits=8,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax percentage captured at batch time",
                        max_digits=5,
                    ),
                ),
                (
                    "certificate_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total certificates across all cases in the batch",
                    ),
                ),
                (
                    "bag_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total drug bags across all cases in the batch",
                    ),
                ),
                (
                    "cert_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "bag_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "certificate_number_range",
                    models.CharField(
                        blank=True,
                        help_text="Certificate number range for the batch (e.g. R4562-R4585)",
                        max_length=255,
                    ),
                ),
                (
                    "invoice_raised_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique Oracle invoice-raised number; completing the cases",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "invoice_raised_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invoice-raised number was recorded",
                        null=True,
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated ZIP package of certificates and cost summary",
                        null=True,
                        upload_to="batches/",
                    ),
                ),
                ("zip_size", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the batch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "db_table": "submissions_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="case",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The batch this case has been included in, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="submissions.batch",
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["-created_at"], name="submissions_created_173f22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["batch_number"], name="submissions_batch_n_f35d0a_idx"
            ),
        ),
    ]
