# Generated by Django 6.0.6 on 2026-06-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0020_batching_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalinvoicefee",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="additionalinvoicefee",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="additionalinvoicefee",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="additionalinvoicefee",
            name="updated_by",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="submissions_submiss_e25547_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="submissions_invoice_6ebba8_idx",
        ),
        migrations.RemoveField(
            model_name="case",
            name="botanist_approved_at",
        ),
        migrations.RemoveField(
            model_name="case",
            name="emails_sent_at",
        ),
        migrations.RemoveField(
            model_name="case",
            name="finance_approved_at",
        ),
        migrations.RemoveField(
            model_name="case",
            name="forensic_hours",
        ),
        migrations.RemoveField(
            model_name="case",
            name="fuel_distance_km",
        ),
        migrations.RemoveField(
            model_name="case",
            name="invoices_generated_at",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="file_hash_at_signing",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="is_locked",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="locked_at",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="signature_embedded_at",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="signature_used_id",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="signed_by",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="signed_pdf_file",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="signed_pdf_size",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="unlocked_by",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="unsigned_pdf_file",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="unsigned_pdf_size",
        ),
        migrations.DeleteModel(
            name="AdditionalInvoiceFee",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        # The signatures app has been removed. Drop its now-orphaned tables.
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS signatures_signatureauditlog CASCADE;",
                "DROP TABLE IF EXISTS signatures_signature CASCADE;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
