# Generated by Django 6.0.6 on 2026-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0021_remove_additionalinvoicefee_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="phase",
            field=models.CharField(
                choices=[
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("batching", "Batching"),
                    ("complete", "Complete"),
                ],
                default="assessment",
                help_text="Current phase of the case workflow",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="from_phase",
            field=models.CharField(
                choices=[
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("batching", "Batching"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case was in before this transition",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="to_phase",
            field=models.CharField(
                choices=[
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("batching", "Batching"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case moved to",
                max_length=30,
            ),
        ),
    ]
