# Generated by Django 6.0.6 on 2026-06-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0023_remap_case_creation_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="additional_notes",
            field=models.TextField(
                blank=True,
                help_text="Section C 'other matters' notes shown on this certificate",
                null=True,
            ),
        ),
    ]
