# Generated by Django 6.0.6 on 2026-06-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0024_certificate_additional_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="certificate_number_range",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated certificate numbers for the batch",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="phase",
            field=models.CharField(
                choices=[
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("batching", "Batching"),
                    ("in_batch", "In Batch"),
                    ("complete", "Complete"),
                ],
                default="assessment",
                help_text="Current phase of the case workflow",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="from_phase",
            field=models.CharField(
                choices=[
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("batching", "Batching"),
                    ("in_batch", "In Batch"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case was in before this transition",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="to_phase",
            field=models.CharField(
                choices=[
                    ("assessment", "Assessment"),
                    ("unsigned_generation", "Unsigned Certificate"),
                    ("batching", "Batching"),
                    ("in_batch", "In Batch"),
                    ("complete", "Complete"),
                ],
                help_text="Phase the case moved to",
                max_length=30,
            ),
        ),
    ]
