# Generated by Django 6.0.6 on 2026-06-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0025_alter_batch_certificate_number_range_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casephasehistory",
            name="reason",
        ),
        migrations.AlterField(
            model_name="casephasehistory",
            name="action",
            field=models.CharField(
                choices=[("advance", "Advanced")],
                help_text="Type of action that caused this transition",
                max_length=20,
            ),
        ),
    ]
