# Generated by Django 6.0.6 on 2026-06-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0026_remove_casephasehistory_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="police_form",
            field=models.FileField(
                blank=True,
                help_text="Optional scanned Priority 3 form used to create this case",
                null=True,
                upload_to="police_forms/",
                verbose_name="Police Priority 3 Form",
            ),
        ),
    ]
