# Generated by Django 6.0.6 on 2026-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0027_case_police_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="is_legacy",
            field=models.BooleanField(
                default=False,
                help_text="True for ETL-imported historical cases that predate the current workflow.",
            ),
        ),
    ]
