# Generated by Django 6.0.6 on 2026-07-07 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0028_case_is_legacy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Priority3Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scanned_image",
                    models.FileField(
                        blank=True,
                        help_text="Scanned Priority 3 form image for this form only",
                        null=True,
                        upload_to="priority3_forms/",
                        verbose_name="Scanned Priority 3 Form",
                    ),
                ),
                (
                    "security_movement_envelope",
                    models.CharField(
                        blank=True,
                        help_text="Security Movement Envelope number for this form's bags",
                        max_length=20,
                        verbose_name="Security Movement Envelope",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("assessment", "Assessment"),
                            ("unsigned_generation", "Unsigned Certificate"),
                            ("batching", "Batching"),
                            ("in_batch", "In Batch"),
                            ("complete", "Complete"),
                        ],
                        default="assessment",
                        help_text="Current phase of this form's workflow",
                        max_length=30,
                    ),
                ),
                (
                    "certificates_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Priority 3 Form",
                "verbose_name_plural": "Priority 3 Forms",
                "db_table": "submissions_priority3form",
                "ordering": ["case", "id"],
            },
        ),
        migrations.RemoveIndex(
            model_name="certificate",
            name="submissions_submiss_9eba8e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="drugbag",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="case",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="case",
            name="certificates_generated_at",
        ),
        migrations.RemoveField(
            model_name="case",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="case",
            name="phase",
        ),
        migrations.RemoveField(
            model_name="case",
            name="police_form",
        ),
        migrations.RemoveField(
            model_name="case",
            name="security_movement_envelope",
        ),
        migrations.AddField(
            model_name="certificate",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The batch this certificate has been included in, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="submissions.batch",
            ),
        ),
        migrations.AddField(
            model_name="priority3form",
            name="case",
            field=models.ForeignKey(
                help_text="The case this Priority 3 form belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="submissions.case",
            ),
        ),
        migrations.AddField(
            model_name="priority3form",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="priority3form",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="priority3form",
            name="last_actioned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last performed a workflow action on this form",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_actioned_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="priority3form",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casephasehistory",
            name="form",
            field=models.ForeignKey(
                blank=True,
                help_text="The Priority 3 form this history entry belongs to, if any",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phase_history",
                to="submissions.priority3form",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="form",
            field=models.OneToOneField(
                default=1,
                help_text="The Priority 3 form this certificate is generated for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate",
                to="submissions.priority3form",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drugbag",
            name="form",
            field=models.ForeignKey(
                default=1,
                help_text="The Priority 3 form this bag belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bags",
                to="submissions.priority3form",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["batch", "-created_at"], name="submissions_batch_i_d71968_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="bags",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="drugbag",
            name="submission",
        ),
    ]
