# Generated by Django 6.0.6 on 2026-07-07 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0029_multi_form_reshape"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="approved_botanist",
            field=models.ForeignKey(
                blank=True,
                help_text="The approved botanist handling this case",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="botanist_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="finance_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="The finance officer handling this case",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finance_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
