# Generated by Django 6.0.6 on 2026-07-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0030_alter_case_approved_botanist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priority3form",
            name="marked_ready",
            field=models.BooleanField(
                default=False,
                help_text="Whether this form's certificate has been reviewed and marked ready for batching",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="certificate_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated certificate number (e.g., R1, R2, R15)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
