# Generated by Django 6.0.6 on 2026-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0031_priority3form_marked_ready_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priority3form",
            name="additional_notes",
            field=models.TextField(
                blank=True,
                help_text="Per-form Section C 'other matters' content for this form's certificate",
                null=True,
                verbose_name="Section C Notes",
            ),
        ),
    ]
