# Generated by Django 6.0.6 on 2026-07-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0032_priority3form_additional_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="additional_notes",
        ),
    ]
