# Generated by Django 6.0.7 on 2026-07-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0035_alter_drugbag_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drugbag",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("plant", "Plant"),
                    ("plant_material", "Plant Material"),
                    ("cutting", "Cutting"),
                    ("stalk", "Stalk"),
                    ("stem", "Stem"),
                    ("seed", "Seed"),
                    ("seed_material", "Seed Material"),
                    ("unknown_seed", "Unknown Seed"),
                    ("seedling", "Seedling"),
                    ("head", "Head"),
                    ("rootball", "Rootball"),
                    ("poppy", "Poppy"),
                    ("poppy_plant", "Poppy Plant"),
                    ("poppy_capsule", "Poppy Capsule"),
                    ("poppy_head", "Poppy Head"),
                    ("poppy_seed", "Poppy Seed"),
                    ("mushroom", "Mushroom"),
                    ("tablet", "Tablet"),
                    ("unknown", "Unknown Material"),
                    ("unsure", "Unsure"),
                ],
                default="plant",
                max_length=20,
            ),
        ),
    ]
