# Generated by Django 6.1 on 2026-08-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0036_alter_drugbag_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="drugbag",
            name="contains_female_plants",
            field=models.BooleanField(
                default=False,
                help_text="Whether this bag contains female plants (marked by botanist during examination)",
            ),
        ),
        migrations.AlterField(
            model_name="drugbag",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("plant", "plant"),
                    ("plant_material", "plant material"),
                    ("cutting", "cutting"),
                    ("stalk", "stalk"),
                    ("stem", "stem"),
                    ("seed", "seed"),
                    ("seed_material", "seed material"),
                    ("unknown_seed", "unknown seed"),
                    ("seedling", "seedling"),
                    ("head", "head"),
                    ("rootball", "rootball"),
                    ("poppy", "poppy"),
                    ("poppy_plant", "poppy plant"),
                    ("poppy_capsule", "poppy capsule"),
                    ("poppy_head", "poppy head"),
                    ("poppy_seed", "poppy seed"),
                    ("mushroom", "mushroom"),
                    ("tablet", "tablet"),
                    ("unknown", "unknown material"),
                    ("unsure", "unsure"),
                ],
                default="plant",
                max_length=20,
            ),
        ),
    ]
