# Generated by Django 6.1.1 on 2026-09-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0037_add_contains_female_plants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casephasehistory",
            name="action",
            field=models.CharField(
                choices=[("advance", "Advanced"), ("repair", "Repaired")],
                help_text="Type of action that caused this transition",
                max_length=20,
            ),
        ),
    ]
