# Generated by Django 6.1.1 on 2026-10-01 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0038_alter_casephasehistory_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in the practice area. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AddField(
            model_name="botanicalassessment",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in the practice area. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in the practice area. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in the practice area. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AddField(
            model_name="drugbag",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in the practice area. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AddField(
            model_name="priority3form",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in the practice area. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brief",
                    models.JSONField(
                        default=dict,
                        help_text="Generated fake Priority 3 forms and the expected values to validate the user's inputs against",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("case_created", "Case created"),
                            ("certificates_generated", "Certificates generated"),
                            ("batched", "Batched"),
                            ("invoiced", "Invoiced"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        help_text="How far through the practice workflow the user has reached",
                        max_length=30,
                    ),
                ),
                (
                    "cert_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Per-session certificate number counter (PRACTICE namespace)",
                    ),
                ),
                (
                    "batch_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Per-session batch number counter (PRACTICE namespace)",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        help_text="The practice case built during this run, once created",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practice_session",
                        to="submissions.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user carrying out this practice run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Practice Session",
                "verbose_name_plural": "Practice Sessions",
                "db_table": "submissions_practicesession",
                "ordering": ["-created_at"],
            },
        ),
    ]
