# Generated by Django 6.1.1 on 2026-10-01 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "submissions",
            "0039_batch_is_practice_botanicalassessment_is_practice_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="practice_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this practice record; null for real data. A user only ever sees their own practice data.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="botanicalassessment",
            name="practice_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this practice record; null for real data. A user only ever sees their own practice data.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="practice_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this practice record; null for real data. A user only ever sees their own practice data.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="practice_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this practice record; null for real data. A user only ever sees their own practice data.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="drugbag",
            name="practice_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this practice record; null for real data. A user only ever sees their own practice data.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_bags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="priority3form",
            name="practice_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this practice record; null for real data. A user only ever sees their own practice data.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in practice mode. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AlterField(
            model_name="botanicalassessment",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in practice mode. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in practice mode. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in practice mode. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AlterField(
            model_name="drugbag",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in practice mode. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.AlterField(
            model_name="priority3form",
            name="is_practice",
            field=models.BooleanField(
                default=False,
                help_text="True for demo/practice records created in practice mode. Hidden from the live application and excluded from all real statistics.",
            ),
        ),
        migrations.DeleteModel(
            name="PracticeSession",
        ),
    ]
