# Generated by Django 5.2.7 on 2025-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PoliceOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "badge_number",
                    models.CharField(
                        blank=True,
                        help_text="Officer's badge number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name or given names.",
                        max_length=100,
                        null=True,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name or surname.",
                        max_length=100,
                        null=True,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("unsworn_officer", "Unsworn Officer"),
                            ("sworn_officer", "Sworn Officer"),
                            ("constable", "Constable"),
                            ("police_constable", "Police Constable"),
                            ("first_class_constable", "First Class Constable"),
                            ("senior_constable", "Senior Constable"),
                            ("detective", "Detective"),
                            (
                                "detective_first_class_constable",
                                "Detective First Class Constable",
                            ),
                            (
                                "detective_senior_constable",
                                "Detective Senior Constable",
                            ),
                            ("senior_detective", "Senior Detective"),
                            ("sergeant", "Sergeant"),
                            ("inspector", "Inspector"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Police Officer",
                "verbose_name_plural": "Police Officers",
            },
        ),
        migrations.CreateModel(
            name="PoliceStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the Police Station / Organisation",
                        max_length=200,
                        verbose_name="Police Station Name",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Police Station address", null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Police Station phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Police Station",
                "verbose_name_plural": "Police Stations",
            },
        ),
    ]
