# Generated by Django 5.2.6 on 2025-09-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policeofficer",
            name="rank",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("unsworn", "Unsworn"),
                    ("unsworn_officer", "Unsworn Officer"),
                    ("officer", "Officer"),
                    ("sworn_officer", "Sworn Officer"),
                    ("constable", "Constable"),
                    ("police_constable", "Police Constable"),
                    ("first_class_constable", "First Class Constable"),
                    ("senior_constable", "Senior Constable"),
                    ("detective", "Detective"),
                    (
                        "detective_first_class_constable",
                        "Detective First Class Constable",
                    ),
                    ("detective_senior_constable", "Detective Senior Constable"),
                    ("senior_detective", "Senior Detective"),
                    ("sergeant", "Sergeant"),
                    ("inspector", "Inspector"),
                    ("conveying_officer", "Conveying Officer"),
                    ("chemist", "Chemist"),
                    ("other", "Other"),
                ],
                default="unsworn",
                max_length=50,
            ),
        ),
    ]
