# Generated by Django 5.2.6 on 2025-09-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police", "0002_remove_unnecessary_etl_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policeofficer",
            name="rank",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("unsworn_officer", "Unsworn Officer"),
                    ("sworn_officer", "Sworn Officer"),
                    ("constable", "Constable"),
                    ("police_constable", "Police Constable"),
                    ("first_class_constable", "First Class Constable"),
                    ("senior_constable", "Senior Constable"),
                    ("detective", "Detective"),
                    (
                        "detective_first_class_constable",
                        "Detective First Class Constable",
                    ),
                    ("detective_senior_constable", "Detective Senior Constable"),
                    ("senior_detective", "Senior Detective"),
                    ("sergeant", "Sergeant"),
                    ("inspector", "Inspector"),
                    ("other", "Other"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
    ]
