# Generated by Django 5.2.7 on 2025-10-21 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invitation_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user accepted their invitation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who sent the invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_last_changed",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user last changed their password",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InviteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the invited user", max_length=254
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("botanist", "Approved Botanist"),
                            ("finance", "Finance Officer"),
                            ("none", "None"),
                        ],
                        help_text="Role to assign to the invited user",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Secure token for invitation activation",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the invitation was created"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the invitation expires (24 hours from creation)"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True, help_text="Whether the invitation is still valid"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether the invitation has been used"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the invitation was used", null=True
                    ),
                ),
                (
                    "external_user_data",
                    models.JSONField(help_text="External user data from IT Assets API"),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation Record",
                "verbose_name_plural": "Invitation Records",
                "db_table": "user_invite_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="invite_token_idx"),
                    models.Index(fields=["email"], name="invite_email_idx"),
                    models.Index(fields=["expires_at"], name="invite_expires_idx"),
                ],
            },
        ),
    ]
