# Generated by Django 5.2.7 on 2025-10-23 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_invitation_accepted_at_user_invited_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="Hashed 4-digit reset code", max_length=255
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the reset code was created"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the reset code expires (24 hours from creation)"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether the reset code has been used"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the reset code was used", null=True
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of verification attempts made"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum allowed verification attempts"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting password reset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Code",
                "verbose_name_plural": "Password Reset Codes",
                "db_table": "password_reset_codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="reset_code_user_idx"),
                    models.Index(fields=["expires_at"], name="reset_code_expires_idx"),
                    models.Index(fields=["is_used"], name="reset_code_used_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_used", False)),
                        fields=("user",),
                        name="unique_active_reset_code_per_user",
                    )
                ],
            },
        ),
    ]
