# Generated by Django 5.2.6 on 2025-09-13 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Mode"),
                            ("dark", "Dark Mode"),
                            ("system", "System"),
                        ],
                        default="system",
                        help_text="User's preferred theme",
                        max_length=10,
                    ),
                ),
                (
                    "submissions_display_mode",
                    models.CharField(
                        choices=[("grid", "Grid View"), ("list", "List View")],
                        default="list",
                        help_text="How to display submissions",
                        max_length=10,
                    ),
                ),
                (
                    "certificates_display_mode",
                    models.CharField(
                        choices=[("grid", "Grid View"), ("list", "List View")],
                        default="list",
                        help_text="How to display certificates",
                        max_length=10,
                    ),
                ),
                (
                    "items_per_page",
                    models.IntegerField(
                        choices=[
                            (10, "10 items"),
                            (25, "25 items"),
                            (50, "50 items"),
                            (100, "100 items"),
                        ],
                        default=25,
                        help_text="Number of items to show per page",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive email notifications"
                    ),
                ),
                (
                    "comment_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when a submission you are involved in receives a comment",
                    ),
                ),
                (
                    "reaction_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when a comment you made is reacted to",
                    ),
                ),
                (
                    "notify_submission_assigned",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when a submission is assigned to you",
                    ),
                ),
                (
                    "notify_phase_changes",
                    models.BooleanField(
                        default=True, help_text="Notify when submission phase changes"
                    ),
                ),
                (
                    "notify_certificate_generated",
                    models.BooleanField(
                        default=True, help_text="Notify when certificates are generated"
                    ),
                ),
                (
                    "notify_invoices_generated",
                    models.BooleanField(
                        default=True, help_text="Notify when invoices are generated"
                    ),
                ),
                (
                    "notify_pdfs_mailed",
                    models.BooleanField(
                        default=True, help_text="Notify when pdfs sent to client"
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("d/m/Y", "DD/MM/YYYY"),
                            ("m/d/Y", "MM/DD/YYYY"),
                            ("Y-m-d", "YYYY-MM-DD"),
                            ("d F Y", "DD Month YYYY"),
                        ],
                        default="d/m/Y",
                        help_text="Preferred date format",
                        max_length=10,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[
                            ("g:i A", "12-hour (2:30 PM)"),
                            ("H:i", "24-hour (14:30)"),
                        ],
                        default="g:i A",
                        help_text="Preferred time format",
                        max_length=10,
                    ),
                ),
                (
                    "reduce_motion",
                    models.BooleanField(
                        default=False, help_text="Reduce animations and motion"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
            },
        ),
    ]
