# Generated by Django 6.0.6 on 2026-06-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_passwordresetcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="comment_notifications",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notify_certificate_generated",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notify_invoices_generated",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notify_pdfs_mailed",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notify_phase_changes",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notify_submission_assigned",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="reaction_notifications",
        ),
    ]
