# Generated by Django 5.2 on 2025-05-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_police'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved_botanist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_finance_officer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_police',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('police', 'Police'), ('finance_officer', 'Finance Officer')], default='none', max_length=20),
        ),
    ]
