# Generated by Django 6.0.6 on 2026-06-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_userpreferences_comment_notifications_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RefreshToken",
        ),
    ]
