# Generated by Django 5.2 on 2025-05-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_approved_botanist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('police', 'Police'), ('finance', 'Finance Officer'), ('botanist', 'Approved Botanist')], default='none', max_length=20),
        ),
    ]
