# Generated by Django 6.0.6 on 2026-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_first_name_to_given_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="given_names",
            field=models.CharField(
                blank=True,
                help_text="Given names (first name / middle names).",
                max_length=100,
                null=True,
                verbose_name="Given Names",
            ),
        ),
    ]
