# Generated by Django 5.2.1 on 2025-05-19 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBCAStaffProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dbca_staff_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('it_asset_id', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('botanist', 'Approved Botanist'), ('finance', 'Finance Officer'), ('none', 'None')], default='none', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='it_asset_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='PoliceStaffProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='police_staff_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('police_id', models.CharField(blank=True, max_length=40, null=True)),
                ('role', models.CharField(choices=[('police_unsworn', 'Police (Unsworn)'), ('police_sworn', 'Police (Sworn)'), ('none', 'None')], default='none', max_length=20)),
                ('station_membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_staff_profile', to='organisations.policestationmembership')),
            ],
        ),
    ]
