# Generated by Django 6.0.7 on 2026-07-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_given_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="inviterecord",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Whether the invited user should be granted admin (staff) access",
            ),
        ),
    ]
