# Generated by Django 5.2.3 on 2025-06-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dbcastaffprofile_remove_user_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policestaffprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='policestaffprofile',
            name='seniority',
            field=models.CharField(choices=[('unset', 'Unset'), ('officer', 'Officer'), ('probationary_constable', 'Probationary Constable'), ('constable', 'Cnstable'), ('detective', 'Detective'), ('first_class_constable', 'First Class Constable'), ('senior_constable', 'Senior Constable'), ('detective_senior_constable', 'Detective Senior Constable'), ('conveying_officer', 'Conveying Officer')], default='officer', max_length=30),
        ),
        migrations.AddField(
            model_name='policestaffprofile',
            name='sworn',
            field=models.BooleanField(default=False),
        ),
    ]
