# Generated by Django 6.1 on 2026-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_is_staff_to_inviterecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_legacy",
            field=models.BooleanField(
                default=False,
                help_text="Legacy users are hidden from selection dropdowns but retain historical data.",
            ),
        ),
    ]
