# Generated by Django 6.1.1 on 2026-10-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_add_is_legacy_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="practice_mode",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user is currently in practice mode",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="practice_mode_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current practice session began; it expires after a day",
                null=True,
            ),
        ),
    ]
