# Generated by Django 6.1.2 on 2026-10-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_userpreferences_practice_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="guide_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show the reference guide outside practice mode",
            ),
        ),
    ]
