name: Docker Build & Push

on:
    push:
        tags:
            - "*"

env:
    REGISTRY: ghcr.io
    REPO_NAME: ${{ github.repository }}

jobs:
    build-frontend:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set up Docker
              run: docker login --username idabblewith --password ${{ secrets.GH_PAT }} ghcr.io

            - name: Extract tag name
              id: tag
              run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            # Production Frontend Build
            - name: Build and push Frontend image
              uses: docker/build-push-action@v6
              with:
                  context: ./frontend
                  push: true
                  build-args: |
                      VITE_PRODUCTION_BASE_URL=https://cannabis.dbca.wa.gov.au/
                      VITE_PRODUCTION_BACKEND_API_URL=https://cannabis.dbca.wa.gov.au/api/v1/
                      VITE_CANNABIS_VERSION=${{ steps.tag.outputs.TAG_NAME }}
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.REPO_NAME }}-frontend:${{ steps.tag.outputs.TAG_NAME }}
                      ${{ env.REGISTRY }}/${{ env.REPO_NAME }}-frontend:latest

    build-backend:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker
              run: docker login --username idabblewith --password ${{ secrets.GH_PAT }} ghcr.io

            - name: Extract tag name
              id: tag
              run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            # Production Backend Build
            - name: Build and push Backend image
              uses: docker/build-push-action@v6
              with:
                  context: ./backend
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.REPO_NAME }}-backend:${{ steps.tag.outputs.TAG_NAME }}
                      ${{ env.REGISTRY }}/${{ env.REPO_NAME }}-backend:latest
